#!/usr/bin/env bash
# 无头 bpy 运行环境（沙箱/CI 内 apt 源不可达时的自愈方案）
#
# 用法:
#   source scripts/3d/blenv.sh
#   python3 scripts/3d/build_xiaoying_v2.py --out /tmp/build/小鹰.blend
#
# 背景:
#   pip 版 bpy 轮子链接了若干 X11/GL 共享库（libGL/libXrender/libxkbcommon...），
#   import 时 ld.so 会做动态解析。但**离屏渲染**(background + Cycles CPU) 的代码路径
#   根本不会调用这些符号，只是链接期的形式依赖。沙箱里装不上真 X11 运行时，
#   因此这里生成「同名 + 同符号」的空桩库骗过动态链接器即可。
#
#   注意：空 .so 不够——libusd_ms.so 会解析 glXMakeCurrent 等具体符号，
#   所以本脚本用 nm 扫描 bpy 全部 .so 的未定义符号，自动补齐 stub 函数。
#
#   沙箱快照回滚会清掉 ~ 下的东西，故设计成**幂等自愈**：每次 source 自检、缺了就重建。

export BLSTUB_DIR="${BLSTUB_DIR:-$HOME/.blstub}"

# 需要伪造的 SONAME 列表
_blstub_libs=(
  libXrender.so.1
  libXi.so.6
  libXxf86vm.so.1
  libXfixes.so.3
  libSM.so.6
  libICE.so.6
  libxkbcommon.so.0
  libGL.so.1
)

_blstub_ok() {
  local l
  for l in "${_blstub_libs[@]}"; do
    [ -f "$BLSTUB_DIR/$l" ] || return 1
  done
  [ -f "$BLSTUB_DIR/.done" ] || return 1
  return 0
}

_blstub_build() {
  command -v gcc >/dev/null 2>&1 || {
    echo "[blenv] 警告: 无 gcc，无法生成桩库" >&2; return 1; }
  command -v nm >/dev/null 2>&1 || {
    echo "[blenv] 警告: 无 nm(binutils)，无法扫描符号" >&2; return 1; }

  mkdir -p "$BLSTUB_DIR" || return 1

  # 1) 扫描 bpy 所有 .so 的未定义 X11/GLX 符号，生成 stub 源码
  python3 - "$BLSTUB_DIR" <<'PY' || return 1
import glob, re, subprocess, sys, os
outdir = sys.argv[1]
pkg = None
for p in sys.path:
    c = os.path.join(p, "bpy", "lib")
    if os.path.isdir(c):
        pkg = os.path.dirname(c); break
if pkg is None:
    cands = glob.glob("/usr/local/lib/python3*/dist-packages/bpy") + \
            glob.glob("/usr/lib/python3*/dist-packages/bpy")
    pkg = cands[0] if cands else None
if pkg is None:
    print("[blenv] 找不到 bpy 包目录，仅生成空桩库"); syms = []
else:
    und = set()
    sos = set()
    for root, _dirs, files in os.walk(pkg):
        for fn in files:
            if ".so" in fn:
                sos.add(os.path.join(root, fn))
    for so in sorted(sos):
        try:
            out = subprocess.run(["nm", "-D", "--undefined-only", so],
                                 capture_output=True, text=True).stdout
        except Exception:
            continue
        for line in out.splitlines():
            parts = line.split()
            if parts:
                und.add(parts[-1])
    # gl*/glX* 全量 + X11 各扩展 + xkbcommon/SM/ICE
    # gl*/glX* 全量 + X11 全家族(X 大写开头) + xkbcommon/SM/ICE
    pat = re.compile(r"^(gl[A-Z]|X[A-Za-z]|_X[A-Za-z]|xkb_|SmcC|IceC|_IceC)")
    syms = sorted(s.split("@")[0] for s in und if pat.match(s))
    syms = sorted(set(syms))
print(f"[blenv] 需要补齐 {len(syms)} 个符号")
with open(os.path.join(outdir, "stub.c"), "w") as f:
    f.write("/* auto-generated by blenv.sh: X11/GLX symbol stubs for headless bpy */\n")
    for s in syms:
        f.write(f"void {s}(void) {{}}\n")
PY

  # 2) 所有桩库都编进同一份 stub.c（符号重复无害，ld.so 取第一个找到的）
  local l
  for l in "${_blstub_libs[@]}"; do
    gcc -shared -fPIC -o "$BLSTUB_DIR/$l" -Wl,-soname,"$l" "$BLSTUB_DIR/stub.c" 2>/dev/null \
      || { echo "[blenv] 生成 $l 失败" >&2; return 1; }
  done
  touch "$BLSTUB_DIR/.done"
  echo "[blenv] 已生成 ${#_blstub_libs[@]} 个 X11/GL 桩库 -> $BLSTUB_DIR"
}

_blstub_ok || _blstub_build

export LD_LIBRARY_PATH="$BLSTUB_DIR:$LD_LIBRARY_PATH"

# 依赖自检提示（不自动装，避免 CI 里意外联网）
python3 - <<'PY' 2>/dev/null || true
missing = []
for m in ("numpy", "PIL", "bpy"):
    try:
        __import__(m)
    except Exception:
        missing.append("pillow" if m == "PIL" else m)
if missing:
    print("[blenv] 缺依赖: " + " ".join(missing))
    print("[blenv] 装: pip install --break-system-packages " + " ".join(
        "bpy==4.2.0" if m == "bpy" else m for m in missing))
PY
